const test = require('node:test')
const assert = require('node:assert/strict')
const { ResourceLeases } = require('../src/runtime/resource-leases.cjs')
const scope = { world: 'world', dimension: 'overworld' }
test('only one local run owns a resource; dimensions and worlds isolate ownership', () => {
  const resources = new ResourceLeases()
  const first = resources.acquire(scope, 'furnace:1,64,0', { agentId: 'A', runId: 1 })
  assert.equal(resources.acquire(scope, 'furnace:1,64,0', { agentId: 'A', runId: 1 }), first)
  assert.throws(() => resources.acquire(scope, 'furnace:1,64,0', { agentId: 'B', runId: 1 }), { code: 'RESOURCE_BUSY' })
  assert.throws(() => resources.acquire(scope, 'furnace:1,64,0', { agentId: 'A', runId: 2 }), { code: 'RESOURCE_BUSY' })
  for (const separate of [{ world: 'other', dimension: 'overworld' }, { world: 'world', dimension: 'nether' }])
    assert(resources.acquire(separate, 'furnace:1,64,0', { agentId: 'B', runId: 1 }))
})
test('unfinished ownership survives handoff and stale cleanup cannot release a resumed run', () => {
  const resources = new ResourceLeases()
  const first = resources.acquire(scope, 'furnace:1,64,0', { agentId: 'A', runId: 1 })
  resources.retain(first)
  assert.throws(() => resources.acquire(scope, 'furnace:1,64,0', { agentId: 'B', runId: 1 }), { code: 'RESOURCE_BUSY' })
  const resumed = resources.acquire(scope, 'furnace:1,64,0', { agentId: 'A', runId: 2 })
  assert.equal(resources.release(first), false)
  assert.equal(resources.valid(resumed), true)
  assert.equal(resources.release(resumed), true)
  assert(resources.acquire(scope, 'furnace:1,64,0', { agentId: 'B', runId: 1 }))
})
